(()=>{'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const groups={
 automotive:{label:'Automotive',match:/auto|automotive|car wash|vehicle|towing|roadside|collision|tire|truck repair/i,subs:[
  ['sales','Sales & Dealers',/dealer|sales/i],['repair','Repair & Mechanics',/repair|mechanic/i],['collision','Collision, Body & Detailing',/collision|auto body|detail/i],['tires','Tires',/tire/i],['inspection','Inspections & Car Wash',/inspection|car wash/i],['towing','Towing & Roadside',/towing|roadside/i],['rental','Car, Van & Truck Rental',/(car|van|truck).*rental|rental.*(car|van|truck)/i]
 ]},
 home:{label:'Home Services & Contractors',match:/hvac|plumb|heating|electric|contractor|home improvement|home repair|house cleaning|painting|remodel|garage door|roof|landscap|tree service|pest|pool service|masonry|chimney|gutter|flooring|fence|interior design|hardscap|cabinet|fireplace|glass|mirror|window repair|drywall|plaster|stucco|tile|marble|excavation|paving|restoration/i,subs:[
  ['emergency-restoration','Water, Fire & Mold Restoration',/water.*restoration|fire.*restoration|mold.*restoration|restoration.*construction/i],['hvac','HVAC & Heating',/hvac|heating|refrigeration/i],['plumbing','Plumbing',/plumb/i],['electrical','Electrical',/electric/i],['roofing','Roofing & Siding',/roof|siding/i],['masonry','Masonry, Chimneys & Hardscaping',/masonry|chimney|hardscap/i],['gutters','Gutters & Gutter Cleaning',/gutter/i],['garage-doors','Garage Doors',/garage door/i],['painting','Painting',/painting|painter/i],['flooring','Flooring',/flooring/i],['tile','Tile & Marble',/tile|marble/i],['drywall','Drywall, Plaster & Stucco',/drywall|plaster|stucco/i],['glass','Glass, Mirrors & Window Repair',/glass|mirror|window repair/i],['excavation','Excavation, Paving & Site Work',/excavation|site work|paving/i],['contractors','General Contracting & Remodeling',/contractor|remodel|home improvement|home repair|construction/i],['cleaning','House Cleaning',/house cleaning|residential.*cleaning/i],['landscape','Landscaping & Tree Services',/landscap|tree service|garden design/i],['pest','Pest Control',/pest/i],['interior','Interior Design & Home Staging',/interior design|home staging/i],['cabinets','Cabinets & Custom Woodwork',/cabinet|custom woodwork/i],['fireplaces','Fireplaces & Outdoor Living',/fireplace|grill|outdoor living/i]
 ]},
 health:{label:'Health, Dental & Wellness',match:/dental|orthodont|oral surgery|endodont|physical therapy|rehabilitation|optometr|eye care|ophthalm|eyewear|audiology|hearing|chiropractic|acupuncture|pharmac|medical|physician|neurolog|psychiatr|mental health|counsel|urgent care|primary care|internal medicine|orthopedic|occupational health|wellness|massage/i,subs:[
  ['dental','Dental & Orthodontics',/dental|orthodont|oral surgery|endodont/i],['rehab','Physical Therapy & Rehabilitation',/physical therapy|rehabilitation/i],['vision','Vision & Eye Care',/optometr|ophthalm|eye care|eyewear|vision/i],['hearing','Audiology & Hearing',/audiology|hearing/i],['chiropractic','Chiropractic',/chiropractic/i],['acupuncture','Acupuncture & Holistic Wellness',/acupuncture|holistic/i],['mental-health','Mental Health & Psychiatry',/mental health|psychiatr|counsel|psycholog/i],['primary','Primary & Urgent Care',/primary care|internal medicine|urgent care|family medicine|occupational health/i],['specialty','Specialty Medical Care',/orthopedic|neurolog|physician|specialty medical|ENT/i],['senior','Nursing & Rehabilitation',/nursing|skilled nursing/i],['pharmacy','Pharmacies, Labs & Medical Supplies',/pharmac|medical supplies|medical equipment|laboratory|diagnostic/i]
 ]},
 pets:{label:'Pets & Veterinary',match:/pet|veterinar|animal hospital|groom|dog walk|pet sit|pet board|dog train/i,subs:[['veterinary','Veterinary & Animal Hospitals',/veterinar|animal hospital/i],['grooming','Pet Grooming',/groom/i],['walking','Dog Walking & Pet Sitting',/dog walk|pet sit/i],['boarding','Boarding, Daycare & Training',/pet board|dog daycare|dog train|pet daycare/i]]},
 professional:{label:'Professional & Financial Services',match:/attorney|legal|account|tax|bookkeep|bank|financial|insurance|notary|real estate|mortgage|appraisal|valuation|mediation|benefit consulting/i,subs:[['legal','Attorneys & Legal Services',/attorney|legal/i],['accounting','Accounting & Tax',/account|tax|bookkeep|CPA/i],['banking','Banks & Financial Services',/bank|financial planning|investment/i],['mortgage','Mortgage Services',/mortgage/i],['insurance','Insurance & Benefits',/insurance|benefit consulting/i],['notary','Notary Services',/notary/i],['real-estate','Real Estate & Property Management',/real estate|property management/i],['appraisal','Appraisal & Valuation',/appraisal|valuation/i],['mediation','Mediation & Conflict Resolution',/mediation|conflict resolution/i]]},
 personal:{label:'Personal Care',match:/barber|salon|beauty|spa|massage|personal care|tailor|alteration|dry clean|laundry|nail|lash|wax|skin care|aesthetic/i,subs:[['hair','Barbers & Salons',/barber|hair salon|salon/i],['nails','Nails, Lashes & Brows',/nail|lash|brow/i],['skin','Skin Care & Aesthetics',/skin care|aesthetic|laser|wax/i],['massage','Massage & Wellness',/massage|body work/i],['tailoring','Tailoring & Alterations',/tailor|alteration/i],['laundry','Laundry & Dry Cleaning',/laundry|dry clean/i]]},
 fitness:{label:'Fitness, Sports & Lessons',match:/fitness|personal training|martial arts|gymnast|swim|cheer|tumbling|music school|music.*lesson|dance school|dance.*lesson|yoga|barre|sports training|weightlifting|tutoring|education/i,subs:[['fitness','Fitness & Personal Training',/fitness|personal training|weightlifting/i],['martial','Martial Arts',/martial arts|karate|taekwondo|jiu-jitsu/i],['gymnastics','Gymnastics, Cheer & Tumbling',/gymnast|cheer|tumbling/i],['swim','Swim Schools',/swim/i],['dance','Dance, Yoga & Barre',/dance|yoga|barre/i],['music','Music Schools & Lessons',/music school|music.*lesson/i],['tutoring','Tutoring & Education',/tutoring|education|college consulting/i],['sports','Sports Training',/sports training|sports performance/i]]},
 creative:{label:'Arts, Creative & Events',match:/artist|creative|photograph|design|gallery|glassblow|media|music|event|wedding|party|function hall|ballroom|conference.*venue|craft|maker|makerspace|workshop|audio production|film production|video production/i,subs:[
  ['venues','Party & Event Venues',/party.*venue|event venue|function hall|ballroom|conference.*venue|wedding.*venue/i],
  ['kids-parties','Kids & Activity Parties',/kids party|birthday part|children.*part|indoor play|family entertainment|arcade|mini golf/i],
  ['event-services','Event Services, Catering & Entertainment',/event service|catering|DJ|entertainment|event planning/i],
  ['artists','Artists & Studios',/artist|art studio|creative studio/i],['photography','Photography',/photograph/i],['design','Design & Creative Services',/design|graphic/i],['media','Media, Audio & Video',/media|audio production|film production|video production/i],['makers','Makerspaces, Crafts & Workshops',/maker|makerspace|craft|glassblow|workshop/i]
 ]},
 lodging:{label:'Hotels & Lodging',match:/hotel|lodging|marriott|sheraton|hampton inn|residence inn|holiday inn/i,subs:[['hotels','Hotels & Lodging',/hotel|lodging|marriott|sheraton|hampton inn|residence inn|holiday inn/i]]},
 family:{label:'Children & Family Services',match:/childcare|preschool|driving school|indoor play|children.*party|family entertainment/i,subs:[['childcare','Childcare & Preschools',/childcare|preschool/i],['parties','Kids Parties & Indoor Play',/indoor play|children.*party|family entertainment/i],['driving','Driving Schools',/driving school/i]]},
 housing:{label:'Housing & Senior Living',match:/apartment|rental housing|assisted living|memory care|home care|senior services|adult day/i,subs:[['apartments','Apartments & Rental Housing',/apartment|rental housing/i],['senior-living','Assisted Living & Memory Care',/assisted living|memory care/i],['home-care','Home Care & Senior Services',/home care|senior services|adult day/i]]},
 shopping:{label:'Shopping & Specialty Retail',match:/grocer|supermarket|produce|warehouse club|international grocer|garden center|nurser|florist|books|shopping|plants|gifts|bicycles|specialty retail|antiques|vintage|jewelry|collectibles|clothing|apparel|sporting goods|department store|beauty supply|musical instrument|home decor|candy|chocolate|convenience store|thrift|wine.*spirit|liquor/i,subs:[['supermarkets','Supermarkets & Groceries',/grocer|supermarket/i],['international','International Grocers',/international grocer/i],['produce','Produce & Specialty Food Retail',/produce|butcher|specialty food|candy|chocolate|deli/i],['convenience','Convenience Stores',/convenience store/i],['garden','Garden, Plants & Florists',/garden|nurser|florist|plants/i],['gifts','Books, Gifts & Specialty Shopping',/books|shopping|gifts/i],['bikes','Bicycles & Sporting Goods',/bicycle|sporting goods/i],['jewelry','Jewelry, Coins & Collectibles',/jewelry|coins|stamps|collectibles/i],['vintage','Antiques, Vintage, Thrift & Home Decor',/antiques|vintage|thrift|home decor|salvage/i],['apparel','Clothing, Apparel & Beauty Supply',/clothing|apparel|beauty supply|dancewear/i],['spirits','Wine & Spirits',/wine.*spirit|liquor/i],['specialty','Other Specialty Retail',/specialty retail|department store|musical instrument/i]]},
 'business-services':{label:'Business & Technology Services',match:/printing|shipping|office|computer|technology|telecom|digital marketing|aviation|flight|aircraft|industrial|building materials|sign|manufactur|fabrication|testing|engineering|architecture|automation|aerospace|composite|electronics|sensor|thermal|machinery|equipment|biotechnology|pharmaceutical|collection services|business services|business consulting|semiconductor|materials testing|distribution|logistics|wholesale|corporate|scientific|environmental|marketing|commercial space|office space|food distribution/i,subs:[['print','Printing, Signs & Promotional Products',/printing|shipping|sign|promotional/i],['tech','Computer, IT & Telecommunications',/computer|technology|telecom|digital/i],['consulting','Business & Professional Consulting',/business consulting|business services/i],['aviation','Aviation Services',/aviation|flight|aircraft|fixed-base/i],['industrial','Industrial & Commercial Supply',/industrial supply|building materials|rigging|commercial supply/i],['engineering','Engineering, Architecture & Manufacturing',/manufactur|fabrication|testing|engineering|architecture|automation|aerospace|composite|electronics|semiconductor|sensor|thermal|machinery|scientific|materials testing|biotechnology|pharmaceutical|environmental/i],['logistics','Distribution, Wholesale & Logistics',/distribution|logistics|wholesale|food distribution/i],['media','Marketing & Media',/marketing|media/i],['space','Office & Commercial Space',/commercial space|office space|office park/i],['equipment','Equipment & Tool Services',/equipment|tool rental/i]]},
 other:{label:'Other Local Services',match:/self storage|moving|funeral|cremation|monument|memorial|headstone|grave marker|cemetery lettering|bronze plaque|florist|sympathy flower|funeral flower|locksmith|security|taxi|shuttle|transportation|truck rental|gas station|cleanout|junk removal/i,subs:[['gas','Gas Stations',/gas station/i],['storage','Storage & Moving',/self storage|storage & moving|moving/i],['funeral','Funeral, Cremation, Memorials & Flowers',/funeral|cremation|monument|memorial|headstone|grave marker|cemetery lettering|bronze plaque|engraving|florist|sympathy flower|funeral flower/i],['security','Locksmiths & Security',/locksmith|security/i],['junk','Junk Removal & Cleanouts',/junk removal|cleanout/i],['transportation','Taxi, Shuttle & Transportation',/taxi|shuttle|transportation|truck rental/i]]}
}
const raw=window.NORWOOD_BUSINESSES||[], businesses=raw.map(b=>Array.isArray(b)?{name:b[0],category:b[1],address:b[2],phone:b[3],website:b[4]}:b);
const text=b=>[b.name,b.category,Array.isArray(b.labels)?b.labels.join(' '):b.labels,Array.isArray(b.tags)?b.tags.join(' '):b.tags].filter(Boolean).join(' ');
function classifyBusiness(b){
 const t=text(b),out=[];
 Object.entries(groups).forEach(([group,g])=>{
  if(!g.match.test(t))return;
  const subs=g.subs.filter(s=>s[2].test(t)).map(s=>s[0]);
  out.push({group,subs});
 });
 return out;
}
businesses.forEach(b=>{b.taxonomy=classifyBusiness(b);});
window.NORWOOD_BUSINESS_TAXONOMY=Object.fromEntries(businesses.map(b=>[String(b.name||'').toLowerCase(),b.taxonomy]));
function card(b){const title=b.website?'<a class="resource-name" href="'+esc(b.website)+'" target="_blank" rel="noopener"><b>'+esc(b.name)+'</b> <span aria-hidden="true">↗</span></a>':'<span class="resource-name resource-name-no-link"><b>'+esc(b.name)+'</b></span>';const details=[b.address,b.phone].filter(Boolean).map(esc).join(' · ');const mapLink=b.address?'<p class="business-map-item-link"><a href="map.html?business='+encodeURIComponent(b.name)+'">Show on map →</a></p>':'';return '<article class="resource-item business-item"><div class="resource-meta"><span class="badge">'+esc(b.category||'Local business')+'</span></div><div class="resource-title-row">'+title+'</div>'+(details?'<p>'+details+'</p>':'')+mapLink+'</article>';}
function parse(){const p=location.hash.slice(1).split('/');return {group:p[0],sub:p[1]};}
function setHash(h){location.hash=h;}
function render(){
 const {group,sub}=parse(),g=groups[group],root=$('#businessDirectory');
 if(!g){root.innerHTML='';return;}
 if(!sub){
   const broad=businesses.filter(b=>b.taxonomy.some(x=>x.group===group)).sort((a,b)=>a.name.localeCompare(b.name));
   const tiles=g.subs.map(s=>{const n=broad.filter(b=>b.taxonomy.some(x=>x.group===group&&x.subs.includes(s[0]))).length;return n?'<a href="#'+group+'/'+s[0]+'"><b>'+esc(s[1])+'</b><small>'+n+' '+(n===1?'business':'businesses')+'</small></a>':''}).join('');
   const subcategories=tiles?'<h3 class="business-filter-heading">Narrow this category</h3><div class="resource-help-grid business-subcategory-grid">'+tiles+'</div>':'';
   const listings=broad.length?broad.map(card).join(''):'<p>No businesses found in this category yet.</p>';
   root.innerHTML='<section class="topic-section selected-resource-topic"><button class="resource-back" type="button">← All business categories</button><p class="eyebrow">BUSINESS CATEGORY</p><h2>'+esc(g.label)+'</h2><p class="sub">'+broad.length+' '+(broad.length===1?'business':'businesses')+' in this category. <a class="business-map-link" href="map.html?businessGroup='+encodeURIComponent(group)+'">View this category on map</a></p>'+subcategories+'<h3 class="business-list-heading">All '+esc(g.label)+' businesses</h3><div class="resource-list">'+listings+'</div></section>';
 } else {
   const s=g.subs.find(x=>x[0]===sub);if(!s){setHash(group);return;}
   const rows=businesses.filter(b=>b.taxonomy.some(x=>x.group===group&&x.subs.includes(sub))).sort((a,b)=>a.name.localeCompare(b.name));
   root.innerHTML='<section class="topic-section selected-resource-topic"><button class="resource-back" type="button">← '+esc(g.label)+'</button><p class="eyebrow">'+esc(g.label.toUpperCase())+'</p><h2>'+esc(s[1])+'</h2><p class="sub"><a class="business-map-link" href="map.html?businessGroup='+encodeURIComponent(group)+'&businessSub='+encodeURIComponent(sub)+'">View these businesses on map</a></p><div class="resource-list">'+(rows.map(card).join('')||'<p>No businesses found in this category yet.</p>')+'</div></section>';
 }
 document.querySelector('.resource-back')?.addEventListener('click',()=>{if(sub)setHash(group);else{history.pushState(null,'',location.pathname);render();document.querySelector('.resource-start')?.scrollIntoView({behavior:'smooth',block:'start'});}});
 requestAnimationFrame(()=>root.scrollIntoView({behavior:'smooth',block:'start'}));
}
window.addEventListener('hashchange',render);render();if($('#businessCount'))$('#businessCount').textContent=businesses.length+' local business listings.';
})();