const map=L.map('detailMap').setView([42.190,-71.198],14);
const basemap=L.tileLayer('https://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles &copy; Esri — Source: Esri, HERE, Garmin, USGS, NGA, EPA, USDA, NPS'}).addTo(map);
let live=L.layerGroup().addTo(map),busStops=L.layerGroup().addTo(map),railStops=L.layerGroup().addTo(map),busShapes=L.layerGroup().addTo(map),railShapes=L.layerGroup().addTo(map);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function vehicleIcon(kind,bearing){const emoji=kind==='bus'?'🚌':'🚆',bg=kind==='bus'?'#F2C100':'#785a91';return L.divIcon({className:'',html:`<div class="vehicle transit-vehicle" style="background:${bg};transform:rotate(${Number.isFinite(bearing)?bearing:0}deg)"><span style="display:block;transform:rotate(${Number.isFinite(bearing)?-bearing:0}deg)">${emoji}</span><i class="direction-arrow">▲</i></div>`,iconSize:[34,34],iconAnchor:[17,17]})}
function dec(str){let i=0,a=0,o=0,c=[];while(i<str.length){let b,s=0,r=0;do{b=str.charCodeAt(i++)-63;r|=(b&31)<<s;s+=5}while(b>=32);a+=(r&1)?~(r>>1):(r>>1);s=0;r=0;do{b=str.charCodeAt(i++)-63;r|=(b&31)<<s;s+=5}while(b>=32);o+=(r&1)?~(r>>1):(r>>1);c.push([a/1e5,o/1e5])}return c}
const get=u=>fetch(u).then(r=>{if(!r.ok)throw Error(r.status);return r.json()});
function direction(route,v){const id=v.attributes.direction_id;return route?.attributes?.direction_destinations?.[id]||route?.attributes?.direction_names?.[id]||`Direction ${id}`}
function busDir(v){return Number(v.attributes.direction_id)===0?'Inbound → Forest Hills':'Outbound → Walpole'}
function stationTimes(pred){const g={i:[],o:[]};pred.forEach(z=>(Number(z.attributes.direction_id)===1?g.i:g.o).push(when(z)));return `<div class=\"dir\"><span>Inbound</span><span>${g.i.slice(0,2).map(esc).join(' · ')||'No prediction'}</span></div><div class=\"dir\"><span>Outbound</span><span>${g.o.slice(0,2).map(esc).join(' · ')||'No prediction'}</span></div>`}
function nearestStop(v,stops){let best=null,bd=1e9;for(const s of stops){const a=s.attributes;if(!a.latitude)continue;const d=(a.latitude-v.attributes.latitude)**2+(a.longitude-v.attributes.longitude)**2;if(d<bd){bd=d;best=s}}return best?.attributes?.name||''}
function statusText(s){return String(s||'Live vehicle').toLowerCase().replaceAll('_',' ').replace(/^./,x=>x.toUpperCase())}
function when(x){const d=x.attributes.departure_time||x.attributes.arrival_time;if(!d)return 'Scheduled time unavailable';const dt=new Date(d),min=Math.round((dt-Date.now())/60000),eta=new Date(Date.now()+Math.max(0,min)*60000).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});return min<=0?`Due · est. ${eta}`:min===1?`1 min · est. ${eta}`:`${min} min · est. ${eta}`}
async function update(){try{const [br,tr,bv,tv,bs,rs,bh,rh]=await Promise.all([
 get('https://api-v3.mbta.com/routes/34E'),get('https://api-v3.mbta.com/routes/CR-Franklin'),get('https://api-v3.mbta.com/vehicles?filter[route]=34E'),get('https://api-v3.mbta.com/vehicles?filter[route]=CR-Franklin'),get('https://api-v3.mbta.com/stops?filter[route]=34E'),get('https://api-v3.mbta.com/stops?filter[route]=CR-Franklin'),get('https://api-v3.mbta.com/shapes?filter[route]=34E'),get('https://api-v3.mbta.com/shapes?filter[route]=CR-Franklin')]);
 live.clearLayers();busStops.clearLayers();railStops.clearLayers();busShapes.clearLayers();railShapes.clearLayers();
 const localBusStops=(bs.data||[]).filter(x=>x.attributes.latitude>42.15&&x.attributes.latitude<42.23&&x.attributes.longitude>-71.24&&x.attributes.longitude<-71.15);(bv.data||[]).filter(v=>v.attributes.latitude).forEach(v=>{const loc=nearestStop(v,localBusStops);L.marker([v.attributes.latitude,v.attributes.longitude],{icon:vehicleIcon('bus',v.attributes.bearing)}).bindPopup(`<b>34E · ${esc(busDir(v))}</b><br>${loc?`Last reported near <span class=\"bus-location\">${esc(loc)}</span><br>`:''}${esc(statusText(v.attributes.current_status))}<br>Updated: ${new Date(v.attributes.updated_at).toLocaleTimeString()}`).addTo(live)});
 (tv.data||[]).filter(v=>v.attributes.latitude).forEach(v=>{const toward=direction(tr.data,v);L.marker([v.attributes.latitude,v.attributes.longitude],{icon:vehicleIcon('train',v.attributes.bearing)}).bindPopup(`<b>Franklin/Foxboro Line · Toward ${esc(toward)}</b><br>${esc(statusText(v.attributes.current_status))}<br>Last report: ${new Date(v.attributes.updated_at).toLocaleTimeString()}`).addTo(live)});
 localBusStops.forEach(x=>L.circleMarker([x.attributes.latitude,x.attributes.longitude],{radius:5,color:'#003B71',weight:2,fillColor:'#fff',fillOpacity:1}).bindPopup(`<b>${esc(x.attributes.name)}</b><br>34E stop`).addTo(busStops));
 const localRail=(rs.data||[]).filter(x=>/Norwood Central|Norwood Depot/i.test(x.attributes.name));
 let stationCards=[];for(const x of localRail){let pred=[];try{pred=(await get(`https://api-v3.mbta.com/predictions?filter[route]=CR-Franklin&filter[stop]=${encodeURIComponent(x.id)}`)).data||[]}catch(e){};pred=pred.filter(z=>(z.attributes.departure_time||z.attributes.arrival_time)).sort((a,b)=>new Date(a.attributes.departure_time||a.attributes.arrival_time)-new Date(b.attributes.departure_time||b.attributes.arrival_time));const times=stationTimes(pred);stationCards.push(`<div class=\"station-arrivals\"><b>${esc(x.attributes.name)}</b>${times}</div>`);L.circleMarker([x.attributes.latitude,x.attributes.longitude],{radius:8,color:'#785a91',weight:3,fillColor:'#fff',fillOpacity:1}).bindTooltip(esc(x.attributes.name),{permanent:true,direction:'top',className:'station-label',offset:[0,-8]}).bindPopup(`<b>🚆 ${esc(x.attributes.name)}</b><br>Franklin/Foxboro Line${times}`).addTo(railStops)}document.querySelector('#stationArrivals').innerHTML=stationCards.join('');
 (bh.data||[]).forEach(x=>x.attributes.polyline&&L.polyline(dec(x.attributes.polyline),{color:'#003B71',weight:5,opacity:.72}).addTo(busShapes));
 (rh.data||[]).forEach(x=>x.attributes.polyline&&L.polyline(dec(x.attributes.polyline),{color:'#785a91',weight:4,opacity:.7,dashArray:'8 6'}).addTo(railShapes));
 document.querySelector('#detailUpdated').textContent=`Live MBTA · ${bv.data?.length||0} bus(es) · ${tv.data?.length||0} train(s) · updated ${new Date().toLocaleTimeString()}`;
 }catch(e){document.querySelector('#detailUpdated').textContent='MBTA live connection unavailable'}}update();setInterval(update,20000);
